version: '3'

services:
  nextjs-app:
    build:
      context: .  # The current directory where the Dockerfile is located
    container_name: nextjs-gallery-app
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
